### ISSUE TITLE
Cannot build/check nft-manager due to missing dependency

### ISSUE THREAD

**Issue by mattdean-dlt** [Aventus-Network-Services/avn-node#4]
First of all it's really great to start to some of the code of the Aventus Network! I recently started to have a look at these pallets and tried to build the `nft-manager`  pallet but this is not possible due to a missing dependency. The error I get is:

```
error: failed to get `pallet-avn` as a dependency of package `pallet-nft-manager v0.7.0 (/<REDACTED>/avn-node/aventus-frame-pallets/nft-manager)`
```

I believe this is because of: https://github.com/Aventus-Network-Services/avn-node/blob/3b4b795b121099058dcf761b7c6b1299dc471513/aventus-frame-pallets/nft-manager/Cargo.toml#L24 which refers to a pallet `pallet-avn` at a path of `../avn` which doesn't exist.

I can provide more details of my toolchain etc. if needed but I think the cause is fairly obvious here.

**Comment by dr-ngubo** [comment]
Hey, @mattdean-dlt it’s great that you’re excited about checking out the Aventus Network code. We appreciate the support! 

We’ve just started open-sourcing our code, starting with two pallets, and have a roadmap to the full release of all pallets. Unfortunately, in this case, the avn pallet required for this build is not meant for release at this stage of the roadmap but it’s not far from now. When we open-source all our code, everyone will be able to build successfully 😁
